version: '3.6'

services:
  db:
    image: mysql:5.6
    container_name: db_app_golang
    command: --init-file /data/application/schema.sql
    volumes: 
      - ./schema.sql:/data/application/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306

  app:
    build: .
    container_name: api_go_app_devOps
    restart: always
    ports:
      - 8080:8080
    environment:
      DB: root:password@(db_app_golang:3306)/library
    links:
      - db
    depends_on: [db]